services:
  - type: web
    name: jobguard-ai-api
    env: docker
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: SCRAPE_DO_KEY
        generateValue: false
      - key: SCRAPER_API_KEY
        generateValue: false
      - key: NLTK_DATA
        value: /opt/render/nltk_data
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    autoDeploy: true
